project:
  type: website
  render: 
    - "slides/"
    - "*.qmd"

website:
  title: "BM432 Data Visualisation Workshop"
  description: "Website for BM432 Data Visualisation Workshop"
  favicon: "assets/images/icon_32.png"
  navbar:
    logo: ./assets/images/masthead_88wide.png
    right:
      - href: index.qmd
        text: Home
      - text: "Introduction"
        menu:
        - text: "Storytelling"
          href: storytelling.qmd
        - text: "Numerical Data"
          href: numerical.qmd
        - text: "Categorical Data"
          href: categorical.qmd
        - text: "Combining Data"
          href: combining.qmd
      - text: "Better Tools"
        menu:
        - text: "Case Study"
          href: better_tools.qmd
        - text: "Interactive Example"
          href: better_interactive.qmd
      - text: "Continuous Variables"
        menu:
        - text: "1D Scatterplot"
          href: univariate_scatter.qmd
        - text: "Box-and-Whisker"
          href: box_and_whisker.qmd
        - text: "Histogram"
          href: histogram.qmd
        - text: "Density Plots"
          href: density.qmd
        - text: "2D Scatterplot"
          href: scatterplot.qmd
      - text: "Categorical Variables"
        menu:
        - text: "Bar Chart/Dot Chart"
          href: bar_chart.qmd
        - text: "Pie Chart"
          href: pie_chart.qmd
        - text: "Proportional Areas"
          href: proportional_area.qmd
      - text: "Exercise"
        menu: 
        - text: "Pre-Workshop Exercise"
        - href: exercise.qmd

  page-footer: 
    left: This site Â© University of Strathclyde 2025

format: 
  html:
    theme: simplex
    toc: true
    css: styles.css
    embed-resources: true

# Freeze output before pushing modifications to the repository when publishing
# Should not need changing
execute:
  freeze: auto

# Add custom callouts
custom-callout:
  callout-case-study:
    title: "Case Study"
    icon-symbol: "ğŸ”"
    color: "#FFA500"
  callout-data:
    icon-symbol: "ğŸ“Š"
    title: "Data Analysis"
    color: "#32CD32"
  callout-discussion:
    title: "Discussion Questions:"
    icon-symbol: "âœ¨"
    color: "#BA55D3"
  callout-microbe:
    title: "Microbe Profile"
    icon-symbol: "ğŸ§«"
    color: "#1E90FF"
  callout-thumbs-up:
    title: "Great job!"
    icon-symbol: "ğŸ‘"
    color: "#008000"
  callout-todo:
    icon-symbol: "ğŸ“"
    color: "pink"
  callout-challenge:
    title: "Challenge"
    icon-symbol: "ğŸ§‘â€ğŸ«"
    color: "aquamarine"
  callout-question:
    title: "Question"
    icon-symbol: "ğŸ™‹"
    color: "yellow"
  callout-questions:
    title: "Questions"
    icon-symbol: "ğŸ™‹ï¸"
    color: "yellow"    
  callout-hints:
    title: "Hints"
    icon-symbol: "ğŸ”ï¸"
    color: "thistle"
  callout-issue:
    title: "Issue"
    icon-symbol: "ğŸ“Šï¸"
    color: "darkorchid"
  callout-solution:
    title: "Solution"
    icon-symbol: "ğŸ“Šï¸"
    color: "goldenrod"


filters:
  - custom-callout
  
bibliography: references.bib
